apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleet-agent
spec:
  selector:
    matchLabels:
      app: fleet-agent
  template:
    metadata:
      labels:
        app: fleet-agent
    spec:
      containers:
      - env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        {{- range $key, $value := .Values.env }}
        - name: {{ $key }}
          value: "{{ $value }}"
        {{- end }}
        {{- if .Values.valsSecret }}
        envFrom:
          - secretRef:
              name: {{ .Values.valsSecret }}
        {{- end }}
        image: '{{ template "system_default_registry" . }}{{.Values.image.repository}}:{{.Values.image.tag}}'
        name: fleet-agent
      serviceAccountName: fleet-agent
      {{- with .Values.fleetAgent.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.fleetAgent.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
