apiVersion: v1
kind: ConfigMap
metadata:
  name: fleet-controller
data:
  config: |
    {
      "agentImage": "{{ template "system_default_registry" . }}{{.Values.agentImage.repository}}:{{.Values.agentImage.tag}}",
      "agentImagePullPolicy": "{{ .Values.agentImage.imagePullPolicy }}",
      "apiServerURL": "{{.Values.apiServerURL}}",
      "apiServerCA": "{{b64enc .Values.apiServerCA}}",
      "agentCheckinInterval": "{{.Values.agentCheckinInterval}}",
      "ignoreClusterRegistrationLabels": {{.Values.ignoreClusterRegistrationLabels}},
      "bootstrap": {
        "paths": "{{.Values.bootstrap.paths}}",
        "repo": "{{.Values.bootstrap.repo}}",
        "secret": "{{.Values.bootstrap.secret}}",
        "branch":  "{{.Values.bootstrap.branch}}",
        "namespace": "{{.Values.bootstrap.namespace}}",
        "agentNamespace": "{{.Values.bootstrap.agentNamespace}}",
      },
      "webhookReceiverURL": "{{.Values.webhookReceiverURL}}",
      {{- if .Values.env }}
      "env":{{toJson .Values.env}},
      {{- end }}
      {{- if .Values.valsSecret }}
      "valsSecret": "{{ .Values.valsSecret }}",
      {{- end }}
      {{- if .Values.valsAgentSecret }}
      "valsAgentSecret": "{{ .Values.valsAgentSecret }}",
      {{- end }}
      "githubURLPrefix": "{{.Values.githubURLPrefix}}"
    }
