apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleet-agent-simulator
spec:
  selector:
    matchLabels:
      app: fleet-agent-simulator
  template:
    metadata:
      labels:
        app: fleet-agent-simulator
    spec:
      containers:
      - env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        {{- range $key, $value := .Values.env }}
        - name: {{ $key }}
          value: {{ $value }}
        {{- end }}
        image: '{{.Values.image.repository}}:{{.Values.image.tag}}'
        args:
        - "fleetagent"
        - "--simulators={{.Values.simulators}}"
        name: fleet-agent-simulator
      serviceAccountName: fleet-agent
